// deploy.js — Hardhat deploy script for the Ethereum-side OBSBridge.
//
//   npx hardhat run deploy.js --network sepolia
//
// Env (loaded from .env via hardhat.config.js):
//   OBS_TOKEN_ADDRESS   ERC-20 OBS token on this chain (required for real use)
//   BRIDGE_OWNER        3/5 multisig that owns the bridge (default: deployer)
//   BRIDGE_RELAYER      initial off-chain relayer        (default: deployer)
//
// Output: appends BRIDGE_CONTRACT_ADDRESS=<addr> to .env.bridge (gitignored).
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  const deployerAddr = await deployer.getAddress();

  // OBSBridge requires a non-zero token address in its constructor, so we
  // refuse to deploy against the zero address (the old behavior would revert
  // on-chain anyway with "OBSBridge: zero token").
  const obsToken = process.env.OBS_TOKEN_ADDRESS;
  if (!obsToken || obsToken === ethers.ZeroAddress) {
    throw new Error(
      "OBS_TOKEN_ADDRESS is not set. Deploy/point to the OBS ERC-20 first, " +
        "then re-run with OBS_TOKEN_ADDRESS=0x..."
    );
  }

  const owner = process.env.BRIDGE_OWNER || deployerAddr;
  const relayer = process.env.BRIDGE_RELAYER || deployerAddr;

  console.log("Deploying OBSBridge with:");
  console.log("  deployer =", deployerAddr);
  console.log("  obsToken =", obsToken);
  console.log("  owner    =", owner);
  console.log("  relayer  =", relayer);

  const OBSBridge = await ethers.getContractFactory("OBSBridge");
  const bridge = await OBSBridge.deploy(obsToken, owner, relayer);
  await bridge.waitForDeployment();

  const addr = await bridge.getAddress();
  console.log(`OBSBridge deployed to: ${addr}`);

  const envPath = path.resolve(__dirname, "../../.env.bridge");
  const stamp = new Date().toISOString();
  fs.appendFileSync(
    envPath,
    `# Generated by contracts/bridge/deploy.js on ${stamp}\n` +
      `BRIDGE_CONTRACT_ADDRESS=${addr}\n`
  );
  console.log(`Wrote BRIDGE_CONTRACT_ADDRESS to ${envPath} (gitignored).`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
