#!/usr/bin/env bash
#
# deploy.sh — Compile and deploy the OBS token (obs_token_v2.nr) to an Aztec
# PXE / sandbox / testnet.
#
# Usage:
#   bash contracts/aztec/deploy.sh
#
# Environment:
#   AZTEC_SANDBOX_URL   PXE RPC endpoint   (default: http://localhost:8080)
#   OBS_OWNER           owner AztecAddress (3/5 multisig). Default: deployer.
#   OBS_MINTER          minter AztecAddress (staking contract). Default: owner.
#   OBS_GUARDIAN        guardian AztecAddress (emergency pause). Default: owner.
#   AZTEC_ACCOUNT_ALIAS account alias / address used to sign the deploy tx.
#
# Output:
#   Appends OBS_TOKEN_ADDRESS=<addr> to .env.aztec (gitignored — never commit).
#
# NOTE: Never pass a real private key on the command line or in this script.
#       Use an aztec-cli account alias / keystore instead.
set -euo pipefail

# Resolve repo root from this script's location so the script works from any cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

SANDBOX_URL="${AZTEC_SANDBOX_URL:-http://localhost:8080}"
ENV_FILE="$REPO_ROOT/.env.aztec"
ARTIFACT="$SCRIPT_DIR/target/obs_token_v2-OBSToken.json"

# Genesis timestamp: now (unix seconds). The inflation schedule starts here.
GENESIS_TS="$(date +%s)"

echo "==> Deploying OBS token to Aztec PXE at: $SANDBOX_URL"

# ── 0. Tooling preflight ──────────────────────────────────────────────────────
if ! command -v aztec-cli &> /dev/null; then
    echo "ERROR: aztec-cli not found." >&2
    echo "  Install : npm install -g @aztec/cli @aztec/aztec.js" >&2
    echo "  Sandbox : docker run -p 8080:8080 -p 9000:9000 aztecprotocol/aztec-sandbox:latest" >&2
    echo "            (or: bash <(curl -s https://install.aztec.network) && aztec start --sandbox)" >&2
    exit 1
fi

if ! command -v aztec-nargo &> /dev/null; then
    echo "ERROR: aztec-nargo not found. Install the Aztec toolchain (aztec-up)." >&2
    exit 1
fi

# ── 1. Reachability check (graceful, non-fatal hint) ─────────────────────────
if ! curl -fsS -o /dev/null --max-time 5 "$SANDBOX_URL" 2>/dev/null; then
    echo "WARN: $SANDBOX_URL did not respond to a probe." >&2
    echo "      Make sure the sandbox is running before the deploy step." >&2
fi

# ── 2. Compile ────────────────────────────────────────────────────────────────
echo "==> Compiling obs_token_v2.nr ..."
( cd "$SCRIPT_DIR" && aztec-nargo compile )

if [ ! -f "$ARTIFACT" ]; then
    # Fall back to whatever JSON artifact the compiler produced.
    ARTIFACT="$(ls -1 "$SCRIPT_DIR"/target/*.json 2>/dev/null | head -n1 || true)"
fi
if [ -z "${ARTIFACT:-}" ] || [ ! -f "$ARTIFACT" ]; then
    echo "ERROR: compiled artifact not found under $SCRIPT_DIR/target/" >&2
    exit 1
fi
echo "    artifact: $ARTIFACT"

# ── 3. Resolve constructor roles ──────────────────────────────────────────────
# constructor(owner, minter, guardian, genesis_ts)
OWNER="${OBS_OWNER:-}"
if [ -z "$OWNER" ]; then
    echo "WARN: OBS_OWNER not set — defaulting owner to the deploying account." >&2
    OWNER="${AZTEC_ACCOUNT_ALIAS:-}"
fi
MINTER="${OBS_MINTER:-$OWNER}"
GUARDIAN="${OBS_GUARDIAN:-$OWNER}"

if [ -z "$OWNER" ]; then
    echo "ERROR: no owner address. Set OBS_OWNER or AZTEC_ACCOUNT_ALIAS." >&2
    exit 1
fi

echo "==> Deploying OBSToken ..."
echo "    owner    = $OWNER"
echo "    minter   = $MINTER"
echo "    guardian = $GUARDIAN"
echo "    genesis  = $GENESIS_TS"

# ── 4. Deploy ─────────────────────────────────────────────────────────────────
DEPLOY_OUTPUT="$(aztec-cli deploy "$ARTIFACT" \
    --rpc-url "$SANDBOX_URL" \
    --args "$OWNER" "$MINTER" "$GUARDIAN" "$GENESIS_TS" 2>&1)" || {
        echo "$DEPLOY_OUTPUT" >&2
        echo "ERROR: deploy failed (see output above)." >&2
        exit 1
    }
echo "$DEPLOY_OUTPUT"

# Parse the deployed address. aztec-cli prints e.g. "Contract deployed at 0x...".
CONTRACT_ADDR="$(echo "$DEPLOY_OUTPUT" \
    | grep -iE "deployed( at|:)" \
    | grep -oE "0x[0-9a-fA-F]{1,64}" \
    | head -n1 || true)"

if [ -z "$CONTRACT_ADDR" ]; then
    echo "WARN: could not parse contract address from deploy output." >&2
    echo "      Inspect the output above and set OBS_TOKEN_ADDRESS manually." >&2
    exit 1
fi

echo "==> OBS Token deployed at: $CONTRACT_ADDR"

# ── 5. Persist (gitignored) ───────────────────────────────────────────────────
{
    echo "# Generated by contracts/aztec/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "AZTEC_SANDBOX_URL=$SANDBOX_URL"
    echo "OBS_TOKEN_ADDRESS=$CONTRACT_ADDR"
} >> "$ENV_FILE"

echo "==> Wrote OBS_TOKEN_ADDRESS to $ENV_FILE (gitignored)."
echo "    Export it for the backend:  export OBS_TOKEN_ADDRESS=$CONTRACT_ADDR"
echo "Done."
