package zk

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestVerifyGroth16_CreditThreshold verifies a real proof generated by
// circuits/test/smoke.js (snarkjs). Run that script first.
func TestVerifyGroth16_CreditThreshold(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokeProofPath := filepath.Join("..", "..", "..", "circuits", "test", "smoke_proof.json")
	data, err := os.ReadFile(smokeProofPath)
	if err != nil {
		t.Skipf("smoke_proof.json not found — run: cd circuits && node test/smoke.js  (got: %v)", err)
	}

	var payload struct {
		ProofJSON     string   `json:"proof_json"`
		CircuitID     string   `json:"circuit_id"`
		PublicInputs  []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal smoke proof: %v", err)
	}

	if !IsCircuitKnown(CircuitID(payload.CircuitID)) {
		t.Fatalf("circuit %s not loaded", payload.CircuitID)
	}

	err = VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs)
	if err != nil {
		t.Fatalf("VerifyGroth16 failed: %v", err)
	}
}

func TestVerifyGroth16_RejectsTamperedProof(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokeProofPath := filepath.Join("..", "..", "..", "circuits", "test", "smoke_proof.json")
	data, err := os.ReadFile(smokeProofPath)
	if err != nil {
		t.Skip("smoke_proof.json not found")
	}

	var payload struct {
		ProofJSON     string   `json:"proof_json"`
		CircuitID     string   `json:"circuit_id"`
		PublicInputs  []string `json:"public_inputs"`
	}
	json.Unmarshal(data, &payload)

	// Tamper the public inputs (raise threshold from 60 to 99)
	if len(payload.PublicInputs) >= 2 {
		payload.PublicInputs[1] = "99"
	}

	err = VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs)
	if err == nil {
		t.Fatal("expected verification to fail for tampered inputs, got nil")
	}
	t.Logf("✓ tampered proof correctly rejected: %v", err)
}

func TestIsCircuitKnown(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	if !IsCircuitKnown(CircuitCreditThreshold) {
		t.Error("credit_threshold should be known")
	}
	if !IsCircuitKnown(CircuitIdentityProof) {
		t.Error("identity_proof should be known")
	}
	if !IsCircuitKnown(CircuitMessageIntegrity) {
		t.Error("message_integrity should be known")
	}
	if !IsCircuitKnown(CircuitStorageProof) {
		t.Error("storage_proof should be known")
	}
	if !IsCircuitKnown(CircuitTokenBalance) {
		t.Error("token_balance should be known")
	}
	if !IsCircuitKnown(CircuitVoteProof) {
		t.Error("vote_proof should be known")
	}
	if IsCircuitKnown(CircuitID("nonexistent_circuit")) {
		t.Error("nonexistent should NOT be known")
	}
}

func TestVerifyGroth16_StorageProof(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokePath := filepath.Join("..", "..", "..", "circuits", "test", "storage_smoke_proof.json")
	data, err := os.ReadFile(smokePath)
	if err != nil {
		t.Skipf("storage_smoke_proof.json not found — run: cd circuits && node test/storage_smoke.js")
	}

	var payload struct {
		ProofJSON    string   `json:"proof_json"`
		CircuitID    string   `json:"circuit_id"`
		PublicInputs []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if err := VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs); err != nil {
		t.Fatalf("storage proof verify failed: %v", err)
	}
}

func TestVerifyGroth16_TokenBalance(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokePath := filepath.Join("..", "..", "..", "circuits", "test", "token_balance_smoke_proof.json")
	data, err := os.ReadFile(smokePath)
	if err != nil {
		t.Skipf("token_balance_smoke_proof.json not found — run: cd circuits && node test/token_balance_smoke.js")
	}

	var payload struct {
		ProofJSON    string   `json:"proof_json"`
		CircuitID    string   `json:"circuit_id"`
		PublicInputs []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if err := VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs); err != nil {
		t.Fatalf("token_balance proof verify failed: %v", err)
	}
}

func TestVerifyGroth16_VoteProof(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokePath := filepath.Join("..", "..", "..", "circuits", "test", "vote_proof_smoke_proof.json")
	data, err := os.ReadFile(smokePath)
	if err != nil {
		t.Skipf("vote_proof_smoke_proof.json not found — run: cd circuits && node test/vote_proof_smoke.js")
	}

	var payload struct {
		ProofJSON    string   `json:"proof_json"`
		CircuitID    string   `json:"circuit_id"`
		PublicInputs []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if err := VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs); err != nil {
		t.Fatalf("vote_proof proof verify failed: %v", err)
	}
}

// TestVerifyGroth16_MsgCountProof verifies a real proof generated by
// circuits/test/msg_count_proof_smoke.js (snarkjs). Run that script first.
// The script also exercises the invalid-input path (conv_count > total_count,
// circuit's consistency constraint) directly against fullProve — a witness
// that violates a hard circom constraint never reaches this Go test at all,
// so that half of the coverage lives in the .js smoke script, not here.
func TestVerifyGroth16_MsgCountProof(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokePath := filepath.Join("..", "..", "..", "circuits", "test", "msg_count_proof_smoke_proof.json")
	data, err := os.ReadFile(smokePath)
	if err != nil {
		t.Skipf("msg_count_proof_smoke_proof.json not found — run: cd circuits && node test/msg_count_proof_smoke.js")
	}

	var payload struct {
		ProofJSON    string   `json:"proof_json"`
		CircuitID    string   `json:"circuit_id"`
		PublicInputs []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if err := VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs); err != nil {
		t.Fatalf("msg_count_proof verify failed: %v", err)
	}
}

// TestVerifyGroth16_MsgCountProof_RejectsTamperedPublicInputs — geçerli bir
// proof'un public input'ları (min_count) sonradan değiştirilirse (Groth16'nın
// public input'lara bağlı olması gerektiği için) doğrulama reddetmeli.
func TestVerifyGroth16_MsgCountProof_RejectsTamperedPublicInputs(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokePath := filepath.Join("..", "..", "..", "circuits", "test", "msg_count_proof_smoke_proof.json")
	data, err := os.ReadFile(smokePath)
	if err != nil {
		t.Skip("msg_count_proof_smoke_proof.json not found")
	}

	var payload struct {
		ProofJSON    string   `json:"proof_json"`
		CircuitID    string   `json:"circuit_id"`
		PublicInputs []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	// public_inputs sırası circuit'teki {public [min_count, epoch, count_commitment]}
	// sırası — min_count ilk eleman.
	if len(payload.PublicInputs) == 0 {
		t.Fatal("expected at least 1 public input (min_count)")
	}
	payload.PublicInputs[0] = "999999"

	err = VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs)
	if err == nil {
		t.Fatal("expected verification to fail for tampered min_count, got nil")
	}
	t.Logf("✓ tampered min_count correctly rejected: %v", err)
}

// TestVerifyGroth16_StreakProof verifies a real proof generated by
// circuits/test/streak_proof_smoke.js (snarkjs). Run that script first.
// The script also exercises the invalid-input path (streak_length > 365,
// circuit's max_check constraint) directly against fullProve.
func TestVerifyGroth16_StreakProof(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokePath := filepath.Join("..", "..", "..", "circuits", "test", "streak_proof_smoke_proof.json")
	data, err := os.ReadFile(smokePath)
	if err != nil {
		t.Skipf("streak_proof_smoke_proof.json not found — run: cd circuits && node test/streak_proof_smoke.js")
	}

	var payload struct {
		ProofJSON    string   `json:"proof_json"`
		CircuitID    string   `json:"circuit_id"`
		PublicInputs []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if err := VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs); err != nil {
		t.Fatalf("streak_proof verify failed: %v", err)
	}
}

// TestVerifyGroth16_StreakProof_RejectsTamperedPublicInputs — geçerli bir
// proof'un public input'ları (min_streak_days) sonradan değiştirilirse
// doğrulama reddetmeli.
func TestVerifyGroth16_StreakProof_RejectsTamperedPublicInputs(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokePath := filepath.Join("..", "..", "..", "circuits", "test", "streak_proof_smoke_proof.json")
	data, err := os.ReadFile(smokePath)
	if err != nil {
		t.Skip("streak_proof_smoke_proof.json not found")
	}

	var payload struct {
		ProofJSON    string   `json:"proof_json"`
		CircuitID    string   `json:"circuit_id"`
		PublicInputs []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	// public_inputs sırası {public [min_streak_days, current_epoch, streak_commitment]}
	// sırası — min_streak_days ilk eleman.
	if len(payload.PublicInputs) == 0 {
		t.Fatal("expected at least 1 public input (min_streak_days)")
	}
	payload.PublicInputs[0] = "999999"

	err = VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs)
	if err == nil {
		t.Fatal("expected verification to fail for tampered min_streak_days, got nil")
	}
	t.Logf("✓ tampered min_streak_days correctly rejected: %v", err)
}
