// Package zk implements Groth16 ZK proof verification for Obscura circuits.
//
// Verification keys are loaded from internal/zk/keys/<circuit>_vkey.json at startup.
// Generated by circuits/build.sh + circuits/distribute.sh.
package zk

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/iden3/go-rapidsnark/types"
	"github.com/iden3/go-rapidsnark/verifier"
)

//go:embed keys/*.json
var embeddedKeys embed.FS

// CircuitID — known Obscura circuits with corresponding vkey files.
type CircuitID string

const (
	CircuitCreditThreshold  CircuitID = "credit_threshold"
	CircuitIdentityProof    CircuitID = "identity_proof"
	CircuitMessageIntegrity CircuitID = "message_integrity"
	CircuitStorageProof     CircuitID = "storage_proof"
	// FAZ 2 (planned): token_balance, vote_proof, age_proof, etc.
)

// Proof — snarkjs Groth16 proof JSON shape.
type Proof struct {
	PiA      []string   `json:"pi_a"`
	PiB      [][]string `json:"pi_b"`
	PiC      []string   `json:"pi_c"`
	Protocol string     `json:"protocol"`
	Curve    string     `json:"curve"`
}

var (
	vkeyMu sync.RWMutex
	vkeys  = map[CircuitID][]byte{}
)

// LoadVerificationKeys loads all known circuit vkeys from disk OR embedded.
// Tries disk first (development), falls back to embedded (production binary).
func LoadVerificationKeys(keysDir string) error {
	circuits := []CircuitID{
		CircuitCreditThreshold,
		CircuitIdentityProof,
		CircuitMessageIntegrity,
		CircuitStorageProof,
	}

	for _, c := range circuits {
		// Try disk first
		diskPath := filepath.Join(keysDir, string(c)+"_vkey.json")
		data, err := os.ReadFile(diskPath)
		if err != nil {
			// Fallback to embedded
			data, err = embeddedKeys.ReadFile("keys/" + string(c) + "_vkey.json")
			if err != nil {
				return fmt.Errorf("vkey not found for %s (disk: %s, embedded: keys/%s_vkey.json): %w",
					c, diskPath, c, err)
			}
		}

		// Validate it parses
		var probe map[string]any
		if err := json.Unmarshal(data, &probe); err != nil {
			return fmt.Errorf("vkey %s invalid JSON: %w", c, err)
		}
		if probe["protocol"] != "groth16" {
			return fmt.Errorf("vkey %s wrong protocol: %v", c, probe["protocol"])
		}

		vkeyMu.Lock()
		vkeys[c] = data
		vkeyMu.Unlock()
	}
	return nil
}

// IsCircuitKnown returns true if the circuit ID has a loaded verification key.
func IsCircuitKnown(circuit CircuitID) bool {
	vkeyMu.RLock()
	defer vkeyMu.RUnlock()
	_, ok := vkeys[circuit]
	return ok
}

// VerifyGroth16 verifies a snarkjs-generated Groth16 proof.
//
// proofJSON: the "proof" object from snarkjs.groth16.fullProve output
// publicSignals: the "publicSignals" array (string-encoded field elements)
//
// Returns nil if valid, error otherwise.
func VerifyGroth16(circuit CircuitID, proofJSON []byte, publicSignals []string) error {
	vkeyMu.RLock()
	vkey, ok := vkeys[circuit]
	vkeyMu.RUnlock()
	if !ok {
		return fmt.Errorf("unknown circuit: %s", circuit)
	}

	// Parse proof into rapidsnark types
	var proof types.ProofData
	if err := json.Unmarshal(proofJSON, &proof); err != nil {
		return fmt.Errorf("proof unmarshal: %w", err)
	}

	zkProof := types.ZKProof{
		Proof:     &proof,
		PubSignals: publicSignals,
	}

	if err := verifier.VerifyGroth16(zkProof, vkey); err != nil {
		return fmt.Errorf("groth16 verify failed: %w", err)
	}
	return nil
}

// LoadedCircuits returns the IDs of all currently loaded circuits.
func LoadedCircuits() []CircuitID {
	vkeyMu.RLock()
	defer vkeyMu.RUnlock()
	out := make([]CircuitID, 0, len(vkeys))
	for c := range vkeys {
		out = append(out, c)
	}
	return out
}
