package zk

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestVerifyGroth16_CreditThreshold verifies a real proof generated by
// circuits/test/smoke.js (snarkjs). Run that script first.
func TestVerifyGroth16_CreditThreshold(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokeProofPath := filepath.Join("..", "..", "..", "circuits", "test", "smoke_proof.json")
	data, err := os.ReadFile(smokeProofPath)
	if err != nil {
		t.Skipf("smoke_proof.json not found — run: cd circuits && node test/smoke.js  (got: %v)", err)
	}

	var payload struct {
		ProofJSON     string   `json:"proof_json"`
		CircuitID     string   `json:"circuit_id"`
		PublicInputs  []string `json:"public_inputs"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		t.Fatalf("unmarshal smoke proof: %v", err)
	}

	if !IsCircuitKnown(CircuitID(payload.CircuitID)) {
		t.Fatalf("circuit %s not loaded", payload.CircuitID)
	}

	err = VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs)
	if err != nil {
		t.Fatalf("VerifyGroth16 failed: %v", err)
	}
}

func TestVerifyGroth16_RejectsTamperedProof(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	smokeProofPath := filepath.Join("..", "..", "..", "circuits", "test", "smoke_proof.json")
	data, err := os.ReadFile(smokeProofPath)
	if err != nil {
		t.Skip("smoke_proof.json not found")
	}

	var payload struct {
		ProofJSON     string   `json:"proof_json"`
		CircuitID     string   `json:"circuit_id"`
		PublicInputs  []string `json:"public_inputs"`
	}
	json.Unmarshal(data, &payload)

	// Tamper the public inputs (raise threshold from 60 to 99)
	if len(payload.PublicInputs) >= 2 {
		payload.PublicInputs[1] = "99"
	}

	err = VerifyGroth16(CircuitID(payload.CircuitID), []byte(payload.ProofJSON), payload.PublicInputs)
	if err == nil {
		t.Fatal("expected verification to fail for tampered inputs, got nil")
	}
	t.Logf("✓ tampered proof correctly rejected: %v", err)
}

func TestIsCircuitKnown(t *testing.T) {
	if err := LoadVerificationKeys("./keys"); err != nil {
		t.Fatalf("load vkeys: %v", err)
	}

	if !IsCircuitKnown(CircuitCreditThreshold) {
		t.Error("credit_threshold should be known")
	}
	if !IsCircuitKnown(CircuitIdentityProof) {
		t.Error("identity_proof should be known")
	}
	if !IsCircuitKnown(CircuitMessageIntegrity) {
		t.Error("message_integrity should be known")
	}
	if IsCircuitKnown(CircuitID("nonexistent_circuit")) {
		t.Error("nonexistent should NOT be known")
	}
}
