// Package zk implements Groth16 ZK proof verification for Obscura circuits.
//
// Verification keys are loaded from internal/zk/keys/<circuit>_vkey.json at startup.
// Generated by circuits/build.sh + circuits/distribute.sh.
package zk

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/iden3/go-rapidsnark/types"
	"github.com/iden3/go-rapidsnark/verifier"
)

//go:embed keys/*.json
var embeddedKeys embed.FS

// CircuitID — known Obscura circuits with corresponding vkey files.
type CircuitID string

const (
	CircuitCreditThreshold  CircuitID = "credit_threshold"
	CircuitIdentityProof    CircuitID = "identity_proof"
	CircuitMessageIntegrity CircuitID = "message_integrity"
	CircuitStorageProof     CircuitID = "storage_proof"
	CircuitTokenBalance     CircuitID = "token_balance"
	CircuitVoteProof        CircuitID = "vote_proof"
	// FAZ 2 (planned): age_proof, etc.
)

// Proof — snarkjs Groth16 proof JSON shape.
type Proof struct {
	PiA      []string   `json:"pi_a"`
	PiB      [][]string `json:"pi_b"`
	PiC      []string   `json:"pi_c"`
	Protocol string     `json:"protocol"`
	Curve    string     `json:"curve"`
}

var (
	vkeyMu sync.RWMutex
	vkeys  = map[CircuitID][]byte{}
)

// expectedPublicSignals — number of public signals (output + public inputs)
// each circuit must emit. Mismatch is rejected before heavy verify.
//
// Counts include circuit outputs + declared public inputs:
//   - credit_threshold: is_above + [threshold, score_commitment, user_hash] = 4
//   - identity_proof:   verified + [did_commitment, nullifier_hash, epoch] = 4
//   - message_integrity: valid + [sender_commitment, message_hash, group_id, nonce] = 5
//   - storage_proof (v2): proof_commitment + [data_commitment, timestamp, ttl, shard_id, epoch] = 6
//   - token_balance: [balance_commitment, nullifier, root, timestamp] = 4
//   - vote_proof: [poll_id, vote_commitment, voter_root, nullifier, timestamp] = 5
var expectedPublicSignals = map[CircuitID]int{
	CircuitCreditThreshold:  4,
	CircuitIdentityProof:    4,
	CircuitMessageIntegrity: 5,
	CircuitStorageProof:     6,
	CircuitTokenBalance:     4,
	CircuitVoteProof:        5,
}

// LoadVerificationKeys loads all known circuit vkeys.
//
// By default (production-safe) only the embedded keys baked into the binary
// at compile time are loaded. Disk-based loading from keysDir is enabled
// ONLY when OBSCURA_ZK_KEYS_FROM_DISK=true. This prevents an attacker who
// gains write access to the data directory from substituting a forged
// verification key and getting forged proofs accepted.
func LoadVerificationKeys(keysDir string) error {
	circuits := []CircuitID{
		CircuitCreditThreshold,
		CircuitIdentityProof,
		CircuitMessageIntegrity,
		CircuitStorageProof,
		CircuitTokenBalance,
		CircuitVoteProof,
	}

	allowDisk := os.Getenv("OBSCURA_ZK_KEYS_FROM_DISK") == "true"

	for _, c := range circuits {
		var (
			data []byte
			err  error
		)

		if allowDisk {
			// Dev/explicit-opt-in path: disk first, then embedded.
			diskPath := filepath.Join(keysDir, string(c)+"_vkey.json")
			data, err = os.ReadFile(diskPath)
			if err != nil {
				data, err = embeddedKeys.ReadFile("keys/" + string(c) + "_vkey.json")
				if err != nil {
					return fmt.Errorf("vkey not found for %s (disk: %s, embedded: keys/%s_vkey.json): %w",
						c, diskPath, c, err)
				}
			}
		} else {
			// Production-safe path: embedded only.
			data, err = embeddedKeys.ReadFile("keys/" + string(c) + "_vkey.json")
			if err != nil {
				return fmt.Errorf("embedded vkey missing for %s (set OBSCURA_ZK_KEYS_FROM_DISK=true to load from %s): %w",
					c, keysDir, err)
			}
		}

		// Validate it parses
		var probe map[string]any
		if err := json.Unmarshal(data, &probe); err != nil {
			return fmt.Errorf("vkey %s invalid JSON: %w", c, err)
		}
		if probe["protocol"] != "groth16" {
			return fmt.Errorf("vkey %s wrong protocol: %v", c, probe["protocol"])
		}

		vkeyMu.Lock()
		vkeys[c] = data
		vkeyMu.Unlock()
	}
	return nil
}

// IsCircuitKnown returns true if the circuit ID has a loaded verification key.
func IsCircuitKnown(circuit CircuitID) bool {
	vkeyMu.RLock()
	defer vkeyMu.RUnlock()
	_, ok := vkeys[circuit]
	return ok
}

// VerifyGroth16 verifies a snarkjs-generated Groth16 proof.
//
// proofJSON: the "proof" object from snarkjs.groth16.fullProve output
// publicSignals: the "publicSignals" array (string-encoded field elements)
//
// Returns nil if valid, error otherwise.
func VerifyGroth16(circuit CircuitID, proofJSON []byte, publicSignals []string) error {
	vkeyMu.RLock()
	vkey, ok := vkeys[circuit]
	vkeyMu.RUnlock()
	if !ok {
		return fmt.Errorf("unknown circuit: %s", circuit)
	}

	// Per-circuit public-signal length validation. Catches forged proofs that
	// pass extra/missing signals before they reach the heavy pairing check.
	if expected, ok := expectedPublicSignals[circuit]; ok && len(publicSignals) != expected {
		return fmt.Errorf("circuit %s expects %d public signals, got %d", circuit, expected, len(publicSignals))
	}

	// Parse proof into rapidsnark types
	var proof types.ProofData
	if err := json.Unmarshal(proofJSON, &proof); err != nil {
		return fmt.Errorf("proof unmarshal: %w", err)
	}

	zkProof := types.ZKProof{
		Proof:     &proof,
		PubSignals: publicSignals,
	}

	if err := verifier.VerifyGroth16(zkProof, vkey); err != nil {
		return fmt.Errorf("groth16 verify failed: %w", err)
	}
	return nil
}

// LoadedCircuits returns the IDs of all currently loaded circuits.
func LoadedCircuits() []CircuitID {
	vkeyMu.RLock()
	defer vkeyMu.RUnlock()
	out := make([]CircuitID, 0, len(vkeys))
	for c := range vkeys {
		out = append(out, c)
	}
	return out
}
