// deploy-token.js — Hardhat deploy script for the Sepolia OBS TEST token.
//
//   npx hardhat run scripts/deploy-token.js --network sepolia
//
// This is a throwaway ERC-20 used only to exercise OBSBridge.lock()/unlock()
// on Sepolia. It has no relation to any mainnet OBS token and no market value.
//
// Env (loaded from .env via hardhat.config.js):
//   OBS_TOKEN_INITIAL_SUPPLY   whole-token units, minted to deployer
//                              (default: 1000000 = 1,000,000 OBS)
//
// Output: appends OBS_TOKEN_ADDRESS=<addr> to .env.bridge (gitignored).
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  const deployerAddr = await deployer.getAddress();

  const supplyWhole = process.env.OBS_TOKEN_INITIAL_SUPPLY || "1000000";
  const initialSupply = ethers.parseUnits(supplyWhole, 18);

  console.log("Deploying OBSToken (Sepolia test token) with:");
  console.log("  deployer      =", deployerAddr);
  console.log("  initialSupply =", supplyWhole, "OBS");

  const OBSToken = await ethers.getContractFactory("OBSToken");
  const token = await OBSToken.deploy(initialSupply);
  await token.waitForDeployment();

  const addr = await token.getAddress();
  console.log(`OBSToken deployed to: ${addr}`);

  const envPath = path.resolve(__dirname, "../../../.env.bridge");
  const stamp = new Date().toISOString();
  fs.appendFileSync(
    envPath,
    `# Generated by contracts/bridge/scripts/deploy-token.js on ${stamp}\n` +
      `OBS_TOKEN_ADDRESS=${addr}\n`
  );
  console.log(`Wrote OBS_TOKEN_ADDRESS to ${envPath} (gitignored).`);
  console.log(
    "Next: set OBS_TOKEN_ADDRESS in .env, then deploy OBSBridge with " +
      "`npm run deploy:sepolia`."
  );
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
